server:
  port: 8080
  connection-timeout-ms: 5000
  read-timeout-ms: 5000

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/139665684873/db-queue

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error